import{a as p,i as s,S as m}from"./assets/vendor-5l-LjSpL.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="https://pixabay.com/api/",h="49327734-00ffb8023b77f666b7f6e293e";function L(n){const t={key:h,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0};return p.get(g,{params:t}).then(o=>o.data.hits).catch(o=>{throw o})}function S(){const n=document.querySelector(".gallery");n.innerHTML=""}function q(n){const t=document.querySelector(".gallery");if(n.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=n.map(({webformatURL:e,largeImageURL:r,tags:a,likes:u,views:d,comments:y,downloads:f})=>`
          <li class="gallery-item">
            <a class="gallery-link" href="${r}">
              <img class="gallery-image" src="${e}" alt="${a}" width="360" height="200" />
            </a>
            <div class="gallery-actions">
              <p><span>Likes</span>${u}</p>
              <p><span>Views</span> ${d}</p>
              <p><span>Comments</span> ${y}</p>
              <p><span>Downloads</span> ${f}</p>
            </div>
          </li>`).join("");t.innerHTML=o,new m(".gallery a").refresh()}function b(){document.querySelector(".loader").classList.add("visually-hidden")}function w(){document.querySelector(".loader").classList.remove("visually-hidden")}const l=document.querySelector("form"),v=document.querySelector("input[name='search-text']");document.querySelector(".gallery");document.querySelector(".loader");const c={title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef7975"};l.addEventListener("submit",n=>{n.preventDefault();const t=v.value.trim();if(!t){s.show(c);return}S(),b(),L(t).then(o=>{if(o.length===0){s.show(c);return}q(o)}).catch(()=>{s.show({title:"Error",message:"Something went wrong! Please try again later."})}).finally(()=>{w(),l.reset()})});
//# sourceMappingURL=index.js.map
